### PR TITLE
Add in start_confirmed_place

### PR DESCRIPTION
**Pull request by sebastianbarry**
composite_trip_creation.py
- Add into the composite_trip_data the start_confirmed_place object

compositetrip.py
- Added in the start_confirmed_place into the object properties definition

### CODE REVIEW

**Comment by sebastianbarry** [comment]
@shankari for visibility

**Comment by sebastianbarry** [comment]
This is the e-mission-server aspect of the ## First Place Addition ## change
Associated e-mission-phone PR: https://github.com/e-mission/e-mission-phone/pull/951

Testing:

* As you can see, start_confirmed_place is read in from the phone by the server

image

**Comment by shankari** [comment]
This looks fine; I can merge once you change the base to the `may_2023_point_release`

**Comment by sebastianbarry** [comment]
Closed this PR in favor of the updated base https://github.com/e-mission/e-mission-server/pull/910

**Pull request closed without merging**
